### ISSUE TITLE
prolonged save-off time is too risky and unnecessary

### ISSUE THREAD

**Issue by demonspork** [endofzero/Minecraft-Sheller#20]
I suggest we have the script create a copy of the world directory that it updates via rsync whenever the overviewer, biome extractor or c10t runs. This allows us to only turn off level saving for seconds rather than 15 or more minutes and we can continue doing all of the operations using this copy of the world directory.  I am working on coming up with a good revision of this script that does it, because what I have is what I have patched together over time and is actually using 3 different shell scripts to accomplish all of this, including an older version of this script.

**Comment by endofzero** [comment]
this has been addressed... (comment in the other post we have)
