### ISSUE TITLE
use --chunklist with minecraft-overviewer to speed things up a bit

### ISSUE THREAD

**Issue by demonspork** [endofzero/Minecraft-Sheller#22]
I find that the way minecraft-overviewer scans chunks for changes takes a lot longer than manually specifying the --chunklist to render, correct me if I am wrong on that, but that is my experience with it.
what I do in my script is

```
if [[ -e $MCOVERVIEWER_CACHE_PATH/lastrun ]]; then
    find $MC_PATH/temp/$WORLD_NAME -newer $MCOVERVIEWER_CACHE_PATH/lastrun -iname *.dat > $MC_PATH/temp/$WORLD_NAME/CHANGELIST
    rm $MCOVERVIEWER_CACHE_PATH/lastrun
else
    find $MC_PATH/temp/$WORLD_NAME -iname *.dat > $MC_PATH/temp/$WORLD_NAME/CHANGELIST
fi
touch $MCOVERVIEWER_CACHE_PATH/lastrun
```

and then when I run the overviewer I just do 

```
nice python $MCOVERVIEWER_PATH/gmap.py $MCOVERVIEWER_OPTIONS --chunklist=$MC_PATH/temp/$WORLD_NAME/CHANGELIST --cachedir=$MCOVERVIEWER_CACHE_PATH $MC_PATH/temp/$WORLD_NAME $MCOVERVIEWER_MAPS_PATH
```

and if you are on a VDS you may find that the system can go into iolock at times, so I use 

```
ionice -c 2 -n 7 nice 
```

preceding any of the rsync and tar commands in the script which to keep them from causing server lag. Generally only CPU usage from minecraft-overviewer has potential to lag the MC server, so either limit the processor cores it uses or use nice before any overviewer command

I considered coaxing that list of chunks out of the rsync command, but that wouldn't be a complete list because the sync command may have been run several times since the last overviewer render, making its list incomplete

on a related note, I also added a section that updates just the signs using contrib/findsigns.py , because my world has gotten so large that I run the overviewer once a day early in the morning when no one is online, so I run 
    minecraft.sh signs
once or twice an hour during the day.

**Comment by endofzero** [comment]
That is with the latest build, correct? Seems they added at least one caching fix the last week of December... It could speed it up.... Although, I don't see why something like this shouldn't' be considered.

**Comment by demonspork** [comment]
my section that runs findsigns.py is useless because findsigns.py isn't what I thought it was. I do have a script that will manually output all of the signs, but it takes a surprising long time to run. And now that I think about it, I may have deleted the last copy of it this morning while tidying up my minecraft stuff.  

Does anyone know of a way that we could check for the status of the minecraft-overviewer command and report it to the server every so often?

**Comment by mattrl** [comment]
A way to check the status of Overviewer and report it to the server?  I used to run tell/say commands to tell me or the server when each step was complete.. rysnc, start, finish, time elapsed, etc.. but I think you want actual status.

You could use tell and I guess you could parse the screen output for the Overviewer run somehow.  You could send a time elapsed and chunks done every 10k chunks or some such.  How to actually do that I wouldn't have a clue.

**Comment by mattrl** [comment]
Back to the topic at hand..

I got this from Overviewer Mega.

CHUNKLIST=`ls /minecraft/logs/*.rsync -t1 | head -n1`

Easy enough from there..

**Comment by demonspork** [comment]
You can't use the rsync log for it because the rsync could have happened several times since the last overviewer render - meaning that the data you pull from the latest rsync isn't the complete changeset since the last overviewer render, just a subset of the most resent rsync

**Comment by mattrl** [comment]
Well you could append to a file and remove duplicates (just assuming there is a super easy tool that does this) before run time.  Surely quicker to remove duplicates from one file than to search dates of thousands of files.

Or store last run date in a file, search for all files after last run date, compare and run.

I never rsync without running overviewer so it's not a problem for me.. plus if a render fails which would be never (unless I am fiddling) I just say 'too bad'.  I tell my users 'If you want something rendered, modify a block in any chunk'.. then the power is in their hands ;)
