### ISSUE TITLE
Planning on making some not-so-minor changes to world operations

### ISSUE THREAD

**Issue by dopeghoti** [endofzero/Minecraft-Sheller#27]
I just did this on my server, and it made things a lot more reliable.

Rather than running things like the biome extractor, mcmap, or the overviewer against the live world while the server is running (even in save-off mode), potentially having my server not saving peoples' work for quite some time (my map has gotten rather large), I now at the start of my routine run save-off, rsync the map into a staging directory, run save-on, and do all my operations on the staging location.  The downside is that this takes a little longer to get started, but it has increased server reliability.

**Comment by endofzero** [comment]
I'm confused... this is already done... the whole reason for 'sync' and the additional commands like 'minecraft.sh cartography sync'...

You even had a pull request for the version of the script that contains that... 

I guess I really don't get where you are coming from on this as we already did this quite some time ago..

**Comment by dopeghoti** [comment]
Perhaps I was having a bit of a brain fart, it looked like that was only partially done when I skimmed the code this morming.  If after I've taken a closer look, it is indeed already done, feel free to utterly disregard this conversation.

It's also entirely possible I was looking at an unrelated script.  Apologies for any confusion.
