### ISSUE TITLE
Backups without a temp file don't work for some systems

### ISSUE THREAD

**Issue by demonspork** [endofzero/Minecraft-Sheller#29]
/home/minecraft/craftbukkit/minecraft.sh: line 362: /bin/tar: Argument list too long

is what I get whenever I try to use the revision of the script for backups now that you have removed the need for a temporary list file. That section of code for the backups needs to be reverted because that part won't work on all systems (particularly mine). I didn't notice that this was happening after updating the version of the script I use and I haven't been backing up for 2 days now, and voila some retarded 13 year old went insane on my server and I went to restore from a backup and I am like OH SNAP

**Comment by dopeghoti** [comment]
Hmm, perhaps we could start using tar -g to perform incremental backups rather than relying on /bin/find; that may fix this issue as well.

I'll look into this; meantime if you need help in undoing the change, I can help you out with that if you have your own fork.

**Comment by demonspork** [comment]
I just found a previous revision of the script and copy/pasted the backup) into place from it.  I think this change probably needs to be reverted for this project entirely

**Comment by endofzero** [comment]
Reverted commit 0e2a76372 on master.

**Comment by endofzero** [comment]
Revert occurred quite awhile ago... closing
