### ISSUE TITLE
Run the server as a different user

### ISSUE THREAD

**Issue by pkkid** [endofzero/Minecraft-Sheller#3]
Maybe this is possible and I am missing it, but we have multible admins on the server.  We're trying to set the owner/group of all the minecraft files to a 'minecraft' user then run the server as that user.  However, in my attempts to do this using the script I start to fall down a permissions rat hole.

**Comment by endofzero** [comment]
What permission issues are you experiencing? The method you describe is how I have my system setup, so it is possible. I login as the user 'minecraft' and issue all script commands from there. All of my minecraft activity is kept inside that user's scope.

I will need some more information to get an idea of what is going wrong.

**Comment by pkkid** [comment]
So, all my minecraft files belong to 'minecraft'.  I am logging in as 'mike' and my account belongs to the 'minecraft' group (but that might not matter).  I basically am curious if I can run minecraft.sh start (as the minecraft user) from a different account.

You stated that you log in as the minecraft user and kickoff the script.  That solution will work for now, but I was trying to not have to do this.  Feel free to make this invalid if I am just using the script wrong.

**Comment by endofzero** [comment]
I really don't think so. I've tested that myself and have found issues with screen not having a terminal to go to if i try to 'su minecraft' from a different account.

That's just in my experience, so it very well may be possible to do what you are attempting, I am just not sure.

I wouldn't say you are using the script wrong, I just don't understand why logging in as 'minecraft' is a problem. Your cronjobs would be local for minecraft allowing for all the cron messages to be piped to just the minecraft user.

**Comment by pkkid** [comment]
Yea, I'll just set the server to kickoff as the minecraft user. -- Lets close this bug, there are more important things to worry about than this one I would say.

**Comment by dopeghoti** [comment]
Make the minecraft user own the script, and set the SUID bit on the script. It will then run with minecraft's permissions, no matter who runs the script.
