### ISSUE TITLE
rsync -a blah blah and cp of EXTRACTEDBIOMES

### ISSUE THREAD

**Issue by demonspork** [endofzero/Minecraft-Sheller#30]
1. We don't need the -z option in the rsync for sync_offline, the -z compresses the data as it is moved, which is unneeded when copying from local directory to local directory
2. Why does the biome) section copy the EXTRACTEDBIOMES from the world-offline into the world folder?  it doubles the size of my backups and is almost completely unnecessary, considering how quickly the biome extractor runs, even from scratch, so keeping a backup copy of it is a huge waste of space.

**Comment by endofzero** [comment]
Yeah... The copy is left over from the first method of biome generation before switching over to rsync. Both have been corrected.
