### ISSUE TITLE
Use -Xincgc instead of -Xms

### ISSUE THREAD

**Issue by ankushg** [endofzero/Minecraft-Sheller#31]
The -Xincgc argument allows the server to run with as little RAM as it wants, but still expand to the -Xmx amount, while doing better garbage collection. The result is less RAM usage and better server performance.

**Comment by ankushg** [comment]
Also, when you use -Xincgc, you don't specify an initial amount of RAM

**Comment by endofzero** [comment]
I'll have to do some testing with that setting first...
