### ISSUE TITLE
mcmap support

### ISSUE THREAD

**Issue by katanacrimson** [endofzero/Minecraft-Sheller#5]
For those of us that prefer mcmap over cartograph, can the script be changed to support mcmap?

mcmap @ minecraftforum: http://www.minecraftforum.net/viewtopic.php?f=25&t=40327

**Comment by endofzero** [comment]
Possible, but I would need to know what is required via command-line. I've already created a branch that can be used to separate the features while being able to patch if required.

**Comment by katanacrimson** [comment]
mcmap -help should list all options iirc

**Comment by endofzero** [comment]
I'm sure it does, but I don't use mcmap and don't have the time to test with the other things I'm working on. I can quickly add a branch that supports it, but I will not take the time to find out all of the required commands.

If you can get that info, I'd be glad to add it to the branch.

**Comment by katanacrimson** [comment]
Here ya go, this is the version I've got at least.  I believe it's the latest (at least I hope it is, because otherwise, I need to redownload and recompile the bugger).

```
~$ ./mcmap -help

mcmap by Zahl - an isometric minecraft map rendering tool. Version 1.9.01

Usage: ./mcmap/mcmap [-from X Z -to X Z] [-night] [-cave] [-noise VAL] [...] WORLDPATH

  -from X Z     sets the coordinate of the chunk to start rendering at
  -to X Z       sets the coordinate of the chunk to end rendering at
                Note: Currently you need both -from and -to to define
                bounds, otherwise the entire world will be rendered.
  -cave         renders a map of all caves that have been explored by players
  -blendcave    overlay caves over normal map; doesn't work with incremental
                rendering (some parts will be hidden)
  -night        renders the world at night using blocklight (torches)
  -skylight     use skylight when rendering map (shadows below trees etc.)
                hint: using this with -night makes a difference
  -noise VAL    adds some noise to certain blocks, reasonable values are 0-20
  -height VAL   maximum height at which blocks will be rendered (1-128)
  -min/max VAL  minimum/maximum Y index (height) of blocks to render (0-127)
  -file NAME    sets the output filename to 'NAME'; default is output.png
  -mem VAL      sets the amount of memory (in MiB) used for rendering. mcmap
                will use incremental rendering or disk caching to stick to
                this limit. Default is 1800.
  -colors NAME  loads user defined colors from file 'NAME'
  -dumpcolors   creates a file which contains the default colors being used
                for rendering. Can be used to modify them and then use -colors
  -north -east -south -west
                controls which direction will point to the *top left* corner
                it only makes sense to pass one of them; East is default
  -blendall     always use blending mode for blocks
  -hell         render the hell/nether dimension of the given world
  -serverhell   force cropping of blocks at the top (use for nether servers)
  -texture NAME extract colors from png file 'NAME'; eg. terrain.png
  -biomes       apply biome colors to grass/leaves; requires that you run                Donkey Kong's biome extractor first on your world
  -biomecolors PATH  load grasscolor.png and foliagecolor.png from 'PATH'

    WORLDPATH is the path of the desired alpha world.

Examples:

./mcmap/mcmap ~/.minecraft/saves/World1
  - This would render your entire singleplayer world in slot 1
./mcmap/mcmap -night -from -10 -10 -to 10 10 ~/.minecraft/saves/World1
  - This would render the same world but at night, and only
    from chunk (-10 -10) to chunk (10 10)
```

Formatting may be slightly weird; if it is, I blame PuTTY.

**Comment by katanacrimson** [comment]
Oh, also, another script I modified (the author wrote it originally I believe, I altered it for my own use) to generate maps with mcmap:
https://gist.github.com/719655

**Comment by endofzero** [comment]
Take a look at this branch https://github.com/endofzero/Minecraft-Sheller/tree/mcmap

Give that a test, CARTO_OPTIONS are where you set mcmaps flags, I added -png -biomes and -blendcave just as examples.

Since you can't specify the filename for outputs, after it is finished, it renames the output and thumb to match the filename scheme of the master branch, It would just be an extra file as the thumb is not generated by c10t.

Not sure how much farther I will get into this... If it is broken, I will try to fix it, but as far as adding features and whathave you... probably not. I will however, try to keep it updated with any fixes I come across.

**Comment by katanacrimson** [comment]
Actually, reading through the params again, it looks like you can set the filename for output files.

```
-file NAME    sets the output filename to 'NAME'; default is output.png
```

**Comment by dopeghoti** [comment]
I use mcmap myself, I may take a stab at this.

**Comment by endofzero** [comment]
I am going to close this as it seems the mcmap branch is working correctly... at least in my brief testing.
